version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: outpost_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VeryStrongPassword@1
      POSTGRES_DB: outpost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: