// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OutPost.Modules.Logistics.Infrastructure.Persistence;

#nullable disable

namespace OutPost.Modules.Logistics.Infrastructure.persistence.migrations
{
    [DbContext(typeof(LogisticsContext))]
    [Migration("20240530191206_Logistics_schema_initialization")]
    partial class Logistics_schema_initialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OutPost.Modules.Logistics.Infrastructure.Persistence.WriteModels.MediativeDeliveryPointWriteModel", b =>
                {
                    b.Property<Guid>("MdpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MdpId");

                    b.ToTable("MediativeDeliveryPointsPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
